# Generated by Django 5.1.3 on 2026-04-11 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientUsageSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subid', models.CharField(db_index=True, max_length=64)),
                ('email', models.CharField(db_index=True, max_length=255)),
                ('used_mb', models.FloatField()),
                ('total_used_bytes', models.BigIntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['recorded_at'],
                'indexes': [models.Index(fields=['subid', 'recorded_at'], name='sub_clientu_subid_f53b2a_idx'), models.Index(fields=['email', 'recorded_at'], name='sub_clientu_email_508fbe_idx')],
            },
        ),
    ]
